version: '3.7'

services:
  arscca-pyramid:
    build: /home/ubuntu/arscca/
    image: arscca-pyramid
    container_name: from-arscca-pyramid
    volumes:
      - type: bind
        source: /home/ubuntu/arscca/
        target: /arscca-pyramid/
      - type: bind
        source: /home/arscca/
        target: /home/arscca/
      - type: bind
        source: /tmp/arscca-pyramid.log
        target: /tmp/arscca-pyramid.log
    links:
      - arscca-redis
    ports:
      - '6543:6543'
    environment:
      - TZ
      - ARSCCA_SLACK_HOOK
      - ARSCCA_STREAMLINE
      - ARSCCA_AXWARE_CAPABLE

  arscca-twisted:
    build: /home/ubuntu/arscca-twisted/
    image: arscca-twisted
    container_name: from-arscca-twisted
    volumes:
      - type: bind
        source: /home/ubuntu/arscca-twisted/
        target: /arscca-twisted/
      - type: bind
        source: /home/arscca/
        target: /home/arscca/
      - type: bind
        source: /tmp/arscca-twisted.log
        target: /tmp/arscca-twisted.log
    links:
      - arscca-redis
    ports:
      - '6544:6544'
    environment:
      - TZ
      - ARSCCA_TWISTED_SLACK_HOOK

  arscca-redis:
    image: redis:5.0.7
    container_name: from-arscca-redis
    volumes:
      - reddata:/data



volumes:
  reddata:
    external:
      name: arscca-redis-data

